### ISSUE TITLE
Charset string problem

### ISSUE THREAD

**Issue by alexdev03** [Exlll/ConfigLib#24]
I put this string (`&7➥ &7Complete the previus task`) inside a List<String> in a record and when I save in the yaml file I get (`&7âž¥ &7Complete the previus task`)
 I tried with the default one and also with bukkit.

![image](https://github.com/Exlll/ConfigLib/assets/56083016/fe837d99-d8c9-4b32-8206-3a47616aae54)
![image](https://github.com/Exlll/ConfigLib/assets/56083016/76dbea09-e7ff-4598-9a75-2a33abd408df)

**Comment by Exlll** [comment]
Hey, @alexdev03!

I pasted that string into an example configuration and saved it; the output looks correct to me: 

![Screenshot from 2023-09-25 01-14-19](https://github.com/Exlll/ConfigLib/assets/5724401/ca9876cc-9a5d-4294-bfcd-d23e0c60359d)


What program did you use to open that file? Perhaps it doesn't properly handle UTF-8?

**Comment by alexdev03** [comment]
The code is run on Linux, on a paper server. I opened it with visual studio code. Also in game I get the same same string as vs code.

**Comment by Exlll** [comment]
As I cannot reproduce this problem (as shown in my screennshots above), I assume that your `.java` files are saved with some encoding other than `UTF-8`. Please make sure that (a) your editor uses `UTF-8` when saving your `.java` files, (b) you call `javac` (the Java compiler) with the `-encoding` option set to `UTF-8`, and (c) that you start your server/the JVM with `-Dfile.encoding` also set to `UTF-8`.

**Comment by alexdev03** [comment]
Intellij has as default encoding type UTF-8, I checked and i'ts correct. I tried by adding `-Dfile.encoding` as startung flag but the issue persists. I also checked the editor and vs code uses UTF-8 to open that file. I tried by opening that java file with vs code and the strings are correct.

I uploaded the classes that I use to create that file. Thanks

[QuestObjective.zip](https://github.com/Exlll/ConfigLib/files/12718372/QuestObjective.zip)

**Comment by Exlll** [comment]
Hm, the contents of the file look fine for me and still don't cause any issues on my system. What happens if you recomile your plugin with the things I said and also regenerate the config file (i.e. delete the old one) with the options I listed on your server? What is the output of `java.nio.charset.Charset.defaultCharset()` on your server?

**Comment by alexdev03** [comment]
I fixed that, I use gradle as library and build system. And the default encoding wasn't UTF-8.  I added `compileJava.options.encoding = 'UTF-8'`
Thanks for the support
