### ISSUE TITLE
Not working jitpack.io

### ISSUE THREAD

**Issue by DizzyMontage13** [Exlll/ConfigLib#31]
**Describe the bug**

respositories {
        mavenCentral()
        google()

        maven {
            name = "exlll"
            url = "https://jitpack.io"
        }

}

dependencies {
        implementation "com.github.Exlll.ConfigLib:configlib-yaml:v4.4.0"
}

> Could not resolve all files for configuration ':paper-core:compileClasspath'.
   > Could not resolve com.github.Exlll.ConfigLib:configlib-yaml:v4.4.0.
     Required by:
         project :paper-core
      > No matching variant of com.github.Exlll.ConfigLib:configlib-yaml:v4.4.0 was found. The consumer was configured to find an API of a library compatible with Java 16, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.github.Exlll.ConfigLib:configlib-yaml:v4.4.0 declares an API of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 16
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability com.github.Exlll.ConfigLib:configlib-yaml:v4.4.0 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 16)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability com.github.Exlll.ConfigLib:configlib-yaml:v4.4.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 16
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability com.github.Exlll.ConfigLib:configlib-yaml:v4.4.0 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 16)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)

![image](https://github.com/Exlll/ConfigLib/assets/124780390/f776fd8c-dc99-4d06-9642-28ae2a01785d)

Not working dependency

**Comment by DizzyMontage13** [comment]
version 1.16.5, java 17 or 16, multi-module gradle project, no kts

**Comment by Exlll** [comment]
Hey, are you sure that's not caused by a type on your side? In the code you pasted above it say `respositories` but the block must be named `repositories`.

**Comment by DizzyMontage13** [comment]
After remove line of importing ur lib its works normal, its said something like Java 16 is not supported. As i said IT works perfectly if remove ur repo its said that crash. It can be typo in upper code bcs i typed it by myself, but in code ur lib crashed

**Comment by Exlll** [comment]
This library requires Java 17+. Please have a look at this issue if you need support for Java < 17: [Shade ConfigLib using Java 8](https://github.com/Exlll/ConfigLib/issues/23)
