### ISSUE TITLE
ConfigLib cuts text?

### ISSUE THREAD

**Issue by KweezyCode** [Exlll/ConfigLib#35]
![image](https://github.com/user-attachments/assets/797d5240-83ab-4893-bd8b-c11abeafdf80)

how to disable that feature? is it a bug or not?

**Comment by Exlll** [comment]
Hi, 

could you paste me your actual code?

**Comment by KweezyCode** [comment]
> Hi,
> 
> could you paste me your actual code? Also, what is the output you expect (i.e. how should the YAML file exactly look like)?

sorry, looks like snakeyaml bug, closing. i have fixed it with
```
tag: |-
  text1
  text2
  ...
```

**Comment by Exlll** [comment]
YAML specifies different (so called) [_block chomping indicators_](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator) that change the behavior of how strings are treated. Glad you found a solution. :+1:
